[env:m5stack-papercolor]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLOCO_PAPERCOLOR_FW_VERSION="\"0.1.0\""
lib_deps =
    m5stack/M5Unified @ ^0.2.15
    m5stack/M5GFX @ ^0.2.21
    links2004/WebSockets @ ^2.6.1
    bblanchon/ArduinoJson @ ^7.2.0
    https://github.com/tzapu/WiFiManager.git#v2.0.17
