apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

helmCharts:
  - name: loco
    releaseName: loco
    namespace: loco-prod
    path: ../../../helm/loco-chart
    valuesInline:
      replicas: 9
