apiVersion: v1
kind: PersistentVolume
metadata:
  name: bootable-disk-pv
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/bootable-disk
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bootable-disk
  namespace: loco
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: bootable-disk-pv
