apiVersion: v1
kind: PersistentVolume
metadata:
  name: win98-disk-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/win98-disk
    type: DirectoryOrCreate
