#!/usr/bin/env bash
# scripts/customize-win98-instance.sh
# Generate per-instance Windows 98 identity configuration for LOCO cluster.
# Produces a .reg file and an AUTOEXEC.BAT snippet that can be injected into
# a QCOW2 image (via virt-customize / guestfish) or served through a QEMU
# shared folder / floppy image at boot time.
#
# Usage:
#   ./scripts/customize-win98-instance.sh <INSTANCE_INDEX>
#   ./scripts/customize-win98-instance.sh 3           # prints to stdout
#   ./scripts/customize-win98-instance.sh 3 -o /tmp   # writes files to /tmp
#
# Depends on: bash ≥ 4 (arithmetic, printf)
# Optional:   virt-customize (to apply directly to a qcow2 image)
set -euo pipefail

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
usage() {
  cat <<'EOF'
Usage: customize-win98-instance.sh <INSTANCE_INDEX> [-o OUTPUT_DIR] [-d DISK_IMAGE]

  INSTANCE_INDEX   Integer 0-8
  -o OUTPUT_DIR    Write .reg and .bat files to this directory (default: stdout)
  -d DISK_IMAGE    Apply the reg file to this QCOW2 image via virt-customize
  -h               Show this help
EOF
  exit 1
}

if [ $# -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  usage
fi

N="$1"; shift

# Validate instance index
if ! [[ "$N" =~ ^[0-8]$ ]]; then
  echo "ERROR: INSTANCE_INDEX must be 0-8, got '$N'" >&2
  exit 1
fi

OUTPUT_DIR=""
DISK_IMAGE=""
while [ $# -gt 0 ]; do
  case "$1" in
    -o) OUTPUT_DIR="$2"; shift 2 ;;
    -d) DISK_IMAGE="$2"; shift 2 ;;
    *)  echo "Unknown option: $1" >&2; usage ;;
  esac
done

# ---------------------------------------------------------------------------
# Derive identity fields (matches instance-identity-spec.md)
# ---------------------------------------------------------------------------
COMPUTER_NAME="LOCO-0${N}"
WORKGROUP="LOCOLAND"
IP_ADDRESS="192.168.10.$((10 + N))"
SUBNET_MASK="255.255.255.0"
GATEWAY="${GUEST_GATEWAY:-192.168.10.$((200 + N))}"
MAC_ADDRESS="52:54:00:10:00:0${N}"
DESCRIPTION="Lego Loco Instance ${N}"

# ---------------------------------------------------------------------------
# Generate Windows 98 registry patch (.reg)
# ---------------------------------------------------------------------------
REG_CONTENT="REGEDIT4

; ============================================================
; Per-instance identity for ${COMPUTER_NAME}
; Generated by customize-win98-instance.sh  (index ${N})
; Matches instance-identity-spec.md
; ============================================================

; --- Computer Name & Workgroup ---
[HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\VxD\\VNETSUP]
\"ComputerName\"=\"${COMPUTER_NAME}\"
\"Workgroup\"=\"${WORKGROUP}\"
\"Comment\"=\"${DESCRIPTION}\"

; --- TCP/IP static configuration (both transport bindings) ---
[HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\Class\\NetTrans\\0000]
\"IPAddress\"=\"${IP_ADDRESS}\"
\"IPMask\"=\"${SUBNET_MASK}\"
\"DefaultGateway\"=\"${GATEWAY}\"

[HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\Class\\NetTrans\\0001]
\"IPAddress\"=\"${IP_ADDRESS}\"
\"IPMask\"=\"${SUBNET_MASK}\"
\"DefaultGateway\"=\"${GATEWAY}\"

; --- NetBIOS over TCP/IP ---
[HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\VxD\\MSTCP]
\"BcastNameQueryCount\"=\"3\"
\"NameSrvQueryCount\"=\"3\"
\"EnableDNS\"=\"0\"
\"NameServer\"=\"\"
\"NodeType\"=\"8\"

; --- Ensure LMHOSTS is not required (pure broadcast/WINS) ---
[HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\VxD\\MSTCP]
\"EnableLMHOSTS\"=\"1\"
\"LMHostFile\"=\"C:\\\\WINDOWS\\\\LMHOSTS\"
"

# ---------------------------------------------------------------------------
# Generate AUTOEXEC.BAT snippet for runtime identity injection
# This is the alternative strategy: the base image runs this at boot to
# read identity vars from a config file on a QEMU-mounted floppy/share.
# ---------------------------------------------------------------------------
BAT_CONTENT="@ECHO OFF
REM ============================================================
REM Per-instance identity for ${COMPUTER_NAME}
REM Generated by customize-win98-instance.sh  (index ${N})
REM Place on floppy image (A:\) or 9pfs share and call from AUTOEXEC.BAT
REM ============================================================

REM Import the registry patch
REGEDIT /S A:\\LOCO-ID.REG

REM Write network identity to a marker file for validation
ECHO ComputerName=${COMPUTER_NAME} > C:\\WINDOWS\\LOCO-ID.TXT
ECHO IPAddress=${IP_ADDRESS} >> C:\\WINDOWS\\LOCO-ID.TXT
ECHO Workgroup=${WORKGROUP} >> C:\\WINDOWS\\LOCO-ID.TXT
ECHO Gateway=${GATEWAY} >> C:\\WINDOWS\\LOCO-ID.TXT
ECHO Index=${N} >> C:\\WINDOWS\\LOCO-ID.TXT

ECHO.
ECHO *** Lego Loco Identity Applied: ${COMPUTER_NAME} (${IP_ADDRESS}) ***
ECHO.
"

# ---------------------------------------------------------------------------
# Generate LMHOSTS file for static NetBIOS name resolution fallback
# ---------------------------------------------------------------------------
LMHOSTS_CONTENT="# LMHOSTS — static NetBIOS name table for LOCOLAND
# Generated by customize-win98-instance.sh
"
for i in $(seq 0 8); do
  LMHOSTS_CONTENT+="192.168.10.$((10 + i))    LOCO-0${i}
"
done

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
if [ -n "$OUTPUT_DIR" ]; then
  mkdir -p "$OUTPUT_DIR"

  REG_FILE="${OUTPUT_DIR}/LOCO-ID-${N}.REG"
  BAT_FILE="${OUTPUT_DIR}/LOCO-ID-${N}.BAT"
  LMH_FILE="${OUTPUT_DIR}/LMHOSTS-${N}"

  # Write with DOS line endings (CR+LF) for Windows 98 compatibility
  printf '%s' "$REG_CONTENT" | sed 's/$/\r/' > "$REG_FILE"
  printf '%s' "$BAT_CONTENT" | sed 's/$/\r/' > "$BAT_FILE"
  printf '%s' "$LMHOSTS_CONTENT" | sed 's/$/\r/' > "$LMH_FILE"

  echo "Written:"
  echo "  Registry patch : $REG_FILE"
  echo "  Boot script    : $BAT_FILE"
  echo "  LMHOSTS file   : $LMH_FILE"
else
  echo "=== Registry Patch (.reg) ==="
  echo "$REG_CONTENT"
  echo ""
  echo "=== Boot Script (.bat) ==="
  echo "$BAT_CONTENT"
  echo ""
  echo "=== LMHOSTS ==="
  echo "$LMHOSTS_CONTENT"
fi

# ---------------------------------------------------------------------------
# Optional: apply directly to a QCOW2 disk image via virt-customize
# ---------------------------------------------------------------------------
if [ -n "$DISK_IMAGE" ]; then
  if ! command -v virt-customize >/dev/null 2>&1; then
    echo "WARNING: virt-customize not found — skipping disk injection." >&2
    echo "Install libguestfs-tools to enable direct image patching." >&2
    exit 0
  fi

  if [ ! -f "$DISK_IMAGE" ]; then
    echo "ERROR: Disk image not found: $DISK_IMAGE" >&2
    exit 1
  fi

  # Write temp files for injection
  TMPDIR=$(mktemp -d)
  trap 'rm -rf "$TMPDIR"' EXIT
  printf '%s' "$REG_CONTENT"      | sed 's/$/\r/' > "$TMPDIR/LOCO-ID.REG"
  printf '%s' "$LMHOSTS_CONTENT"  | sed 's/$/\r/' > "$TMPDIR/LMHOSTS"

  echo "Injecting identity into $DISK_IMAGE ..."
  virt-customize -a "$DISK_IMAGE" \
    --upload "$TMPDIR/LOCO-ID.REG:/WINDOWS/LOCO-ID.REG" \
    --upload "$TMPDIR/LMHOSTS:/WINDOWS/LMHOSTS" \
    --firstboot-command 'REGEDIT /S C:\WINDOWS\LOCO-ID.REG'

  echo "Disk image patched successfully."
fi
