#!/usr/bin/env bash
# trigger_github_actions.sh -- Demonstrate how to trigger the GitHub Actions workflow

echo "🚀 GitHub Actions Workflow Trigger Guide"
echo "========================================"
echo ""

echo "📋 Available Trigger Methods:"
echo ""

echo "1️⃣  **Automatic Trigger** (Recommended)"
echo "   Pushes to main branch automatically trigger the workflow"
echo "   Command:"
echo "   git add ."
echo "   git commit -m 'Add snapshot functionality with pre-built image support'"
echo "   git push origin HEAD"
echo ""

echo "2️⃣  **Manual Trigger with Snapshots**"
echo "   Use GitHub CLI to manually trigger with snapshot building"
echo "   Command:"
echo "   gh workflow run build-qemu.yml -f build_snapshots=true -f image_tag=v1.0.0"
echo ""

echo "3️⃣  **Manual Trigger (Container Only)**"
echo "   Build just the QEMU container without snapshots"
echo "   Command:"
echo "   gh workflow run build-qemu.yml -f build_snapshots=false"
echo ""

echo "📊 **Monitor Workflow Progress:**"
echo "   - GitHub Actions tab: https://github.com/<owner>/<repo>/actions"
echo "   - CLI monitoring: gh run watch"
echo "   - Logs: gh run view --log"
echo ""

echo "🎯 **What the Workflow Does:**"
echo "   ✅ Builds QEMU container with snapshot support"
echo "   ✅ Builds pre-configured snapshots (base, games, productivity)"
echo "   ✅ Pushes images to GitHub Container Registry"
echo "   ✅ Runs security scans with Trivy"
echo "   ✅ Tests integration with Kind clusters"
echo "   ✅ Generates SBOMs for compliance"
echo "   ✅ Creates releases with deployment instructions"
echo ""

echo "🏗️  **Expected Outputs:**"
echo "   Container Images:"
echo "   - ghcr.io/mroie/qemu-loco:latest"
echo "   - ghcr.io/mroie/qemu-loco:<commit-sha>"
echo ""
echo "   Snapshot Images:"
echo "   - ghcr.io/mroie/qemu-snapshots:win98-base"
echo "   - ghcr.io/mroie/qemu-snapshots:win98-games"
echo "   - ghcr.io/mroie/qemu-snapshots:win98-productivity"
echo ""

echo "🔧 **Using Published Images:**"
echo "   # Pull and run locally"
echo "   docker pull ghcr.io/mroie/qemu-loco:latest"
echo ""
echo "   # Deploy to Kubernetes with snapshots"
echo "   helm install loco helm/loco-chart/ \\"
echo "     --set emulator.image.repository=ghcr.io/mroie/qemu-loco \\"
echo "     --set emulator.usePrebuiltSnapshot=true \\"
echo "     --set emulator.snapshotRegistry=ghcr.io/mroie/qemu-snapshots \\"
echo "     --set emulator.snapshotTag=win98-base"
echo ""

echo "✅ Ready to deploy snapshot functionality!"
