apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loco.fullname" . }}-backend
  namespace: {{ include "loco.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "loco.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "loco.fullname" . }}-backend
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: backend
        image: {{ include "loco.image" (dict "root" . "image" .Values.backend.image "tag" .Values.backend.tag) }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.backend.servicePort }}
        volumeMounts:
        - name: instances-config
          mountPath: /app/config/instances.json
          subPath: instances.json
        - name: status-config
          mountPath: /app/config/status.json
          subPath: status.json
      volumes:
      - name: instances-config
        configMap:
          name: {{ include "loco.fullname" . }}-instances
      - name: status-config
        configMap:
          name: {{ include "loco.fullname" . }}-status
