apiVersion: v1
kind: Service
metadata:
  name: {{ include "loco.fullname" . }}-backend
  namespace: {{ include "loco.namespace" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "loco.fullname" . }}-backend
  ports:
  - name: http
    port: {{ .Values.backend.servicePort }}
    targetPort: {{ .Values.backend.servicePort }}
