apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loco.fullname" . }}-instances
  namespace: {{ include "loco.namespace" . }}
  labels:
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: lego-loco-cluster
    app.kubernetes.io/name: lego-loco-config
data:
  instances.json: |
    [
    {{- $name := include "loco.fullname" . }}
    {{- $replicas := int .Values.replicas }}
    {{- range $i := until $replicas }}
      { "id": "instance-{{ $i }}", "streamUrl": "http://{{ $name }}-emulator-{{ $i }}:{{ $.Values.emulator.servicePort }}" }{{ if lt (add1 $i) $replicas }},{{ end }}
    {{- end }}
    ]
