apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "loco.fullname" . }}-emulator
  namespace: {{ include "loco.namespace" . }}
spec:
  serviceName: {{ include "loco.fullname" . }}-emulator
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "loco.fullname" . }}-emulator
  template:
    metadata:
      labels:
        app: {{ include "loco.fullname" . }}-emulator
    spec:
      containers:
      - name: emulator
        image: {{ include "loco.image" (dict "root" . "image" .Values.emulator.image "tag" .Values.emulator.tag) }}
        imagePullPolicy: {{ .Values.emulator.imagePullPolicy }}
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
        ports:
        - containerPort: {{ .Values.emulator.servicePort }}
        volumeMounts:
        - name: disk
          mountPath: /images
          readOnly: {{ .Values.emulator.diskReadOnly }}
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: {{ .Values.emulator.diskPVC }}
