apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.emulator.diskPVC }}-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /tmp/{{ .Values.emulator.diskPVC }}
    type: DirectoryOrCreate
