apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.emulator.diskPVC }}
  namespace: {{ include "loco.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
