apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: loco
    releaseName: loco
    namespace: loco
    path: ../../helm/loco-chart
    valuesInline:
      replicas: 1
