name: Build and Push QEMU Docker Image

on:
  push:
    branches: [ main, master ]
    paths:
      - 'containers/qemu/**'
      - 'scripts/download_and_run_qemu.sh'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'containers/qemu/**'
      - 'scripts/download_and_run_qemu.sh'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: qemu-loco

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./containers/qemu
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Update deployment script
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        # Update the download_and_run_qemu.sh script to use the published image
        sed -i 's/docker build -t qemu-loco .\/containers\/qemu/docker pull ${{ env.REGISTRY }}\/${{ github.repository_owner }}\/${{ env.IMAGE_NAME }}:latest \&\& docker tag ${{ env.REGISTRY }}\/${{ github.repository_owner }}\/${{ env.IMAGE_NAME }}:latest qemu-loco/' scripts/download_and_run_qemu.sh
