name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
      - name: Install Node dependencies
        run: |
          cd backend && npm install && cd ..
          cd frontend && npm install && npm run build && cd ..

  integration:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm qemu-system-x86 qemu-kvm wine gstreamer1.0-tools pulseaudio docker.io tcpdump netcat-openbsd
      - name: Install Node dependencies
        run: |
          cd backend && npm install && cd ..
      - uses: helm/kind-action@v1.9.0
        with:
          version: v0.22.0
      - name: Deploy cluster
        run: kubectl apply -k kustomize/base
      - name: Wait for cluster
        run: kubectl wait --for=condition=Ready pod --all --timeout=300s
      - name: Run network tests
        run: bash k8s-tests/test-network.sh
      - name: Run TCP tests
        run: bash k8s-tests/test-tcp.sh
      - name: Run broadcast tests
        run: bash k8s-tests/test-broadcast.sh
      - name: Upload integration logs
        uses: actions/upload-artifact@v3
        with:
          name: integration-logs
          path: k8s-tests/logs

  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
      - name: Install Node dependencies
        run: |
          cd backend && npm install && cd ..
      - name: Start services
        run: scripts/start_test_services.sh
      - name: Run websocket tests
        run: bash k8s-tests/test-websocket.sh
      - name: Stop services
        if: always()
        run: scripts/stop_test_services.sh
      - name: Upload e2e logs
        uses: actions/upload-artifact@v3
        with:
          name: e2e-logs
          path: k8s-tests/logs

  e2e-live:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm qemu-system-x86 qemu-kvm wine gstreamer1.0-tools pulseaudio docker.io tcpdump netcat-openbsd
      - name: Install Node dependencies
        run: |
          cd backend && npm install && cd ..
      - uses: helm/kind-action@v1.9.0
        with:
          version: v0.22.0
      - name: Deploy cluster
        run: kubectl apply -k kustomize/base
      - name: Wait for cluster
        run: kubectl wait --for=condition=Ready pod --all --timeout=300s
      - name: Start forwards
        run: scripts/start_live_cluster.sh
      - name: Run websocket tests against cluster
        env:
          STREAM_CONFIG: /tmp/live_instances.json
        run: bash k8s-tests/test-websocket.sh
      - name: Stop cluster forwards
        if: always()
        run: scripts/stop_live_cluster.sh
      - name: Upload live e2e logs
        uses: actions/upload-artifact@v3
        with:
          name: live-e2e-logs
          path: k8s-tests/logs
