name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm qemu-system-x86 qemu-kvm wine gstreamer1.0-tools pulseaudio docker.io tcpdump netcat-openbsd
      - name: Install Node dependencies
        run: |
          cd backend && npm install && cd ..
          cd frontend && npm install && cd ..
      - uses: helm/kind-action@v1.9.0
        with:
          version: v0.22.0
      - name: Run network tests
        run: bash k8s-tests/test-network.sh
      - name: Run TCP tests
        run: bash k8s-tests/test-tcp.sh
      - name: Run broadcast tests
        run: bash k8s-tests/test-broadcast.sh
      - name: Run websocket tests
        run: bash k8s-tests/test-websocket.sh
      - name: Upload test logs
        uses: actions/upload-artifact@v3
        with:
          name: k8s-test-logs
          path: k8s-tests/logs
