name: Build Win98 SoftGPU Image

on:
  push:
    branches: [ build_qemu_softgpu ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mroie/lego-loco-cluster/win98-softgpu
  BOOT_IMAGE_ID: FabhMDKwF7Uu1XXsPpAycRhWSYDXqQEH

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      
      - name: Download bootable Win98 image
        run: |
          # Install gdown for reliable Google Drive downloads
          pip install gdown
          
          # Download the Win98 image using gdown (handles large files properly)
          gdown "https://drive.google.com/uc?id=${{ env.BOOT_IMAGE_ID }}" -O containers/qemu-softgpu/win98_softgpu.qcow2
          
          # Verify the download was successful
          if [ $(stat -c%s containers/qemu-softgpu/win98_softgpu.qcow2) -lt 1000000 ]; then
            echo "❌ Download failed - file too small ($(stat -c%s containers/qemu-softgpu/win98_softgpu.qcow2) bytes)"
            echo "File content:"
            head -c 500 containers/qemu-softgpu/win98_softgpu.qcow2
            exit 1
          fi
          
          echo "✅ Download successful - $(stat -c%s containers/qemu-softgpu/win98_softgpu.qcow2) bytes"
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: containers/qemu-softgpu
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
