name: Build Win98 SoftGPU Image

on:
  push:
    branches: [ main ]
    paths:
      - 'containers/qemu-sfotgpu/**'
      - '.github/workflows/win98-softgpu.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: containers/qemu-sfotgpu
          push: true
          tags: youruser/win98-softgpu:latest
          platforms: linux/amd64,linux/arm64
